{% set name = "nlp-preprocessing-pipelines" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ PREPROCESSING_WRAPPERS_VERSION }}"

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}

requirements:
  build:
    - python
    - stanza>=1.3,<1.4
    - spacy>=3.0,<3.3
    - overrides>=6.0.0,<7.0.0
  run:
    - python
    - stanza>=1.3,<1.4
    - spacy>=3.0,<3.3
    - overrides>=6.0.0,<7.0.0
source:
  path: ../../

build:
  noarch: python
