{% set name = "ipa-core" %}
{% set data = load_setup_py_data() %}

package:
  name: "{{ name|lower }}"
  version: "{{ IPA_VERSION }}"

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}

requirements:
  build:
    - python
    - stanza>=1.3,<1.5
    - spacy>=3.0,<3.5
    - overrides>=6.0,<7.4
  run:
    - python
    - stanza>=1.3,<1.5
    - spacy>=3.0,<3.5
    - overrides>=6.0,<7.4
source:
  path: ../../

build:
  noarch: python
