repos:
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

default_language_version:
    python: python3
