repos:
-   repo: https://github.com/ambv/black
    rev: 22.12
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.10.8
    hooks:
    - id: flake8

default_language_version:
    python: python3
