name: Upload Python Package to Conda

on:
  release:
    types: [published]

env:
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          python-version: 3.9
          activate-environment: "build-nlp-preprocessing-wrappers"
          channels: riccorl

      - name: Setup conda env
        run: |
          conda install -c defaults anaconda-client conda-build
      - name: Extract version
        run: echo "PREPROCESSING_WRAPPERS_VERSION=`python setup.py --version`" >> $GITHUB_ENV

      - name: Build conda packages
        run: |
          conda info
          conda list
          conda-build -c riccorl -c conda-forge -c stanfordnlp .github/conda

      - name: Upload to Anaconda
        run: anaconda upload `conda-build .github/conda --output` --force
